version: '2'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo/:/data/db 
    environment:
      - "TZ=Europe/Riga"

  back_end:
    build: ./flask_back_end
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/uploads
    environment:
      - "TZ=Europe/Riga"
    depends_on:
      - mongo
    links:
      - mongo


  front_end:
    build: ./front
    restart: always
    ports:
      - "80:8080"
    environment:
      - "TZ=Europe/Riga"
  

